# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version used to build the docs.
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - htmlzip

# Install the project and its docs dependencies from pyproject.toml.
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
